source 'https://github.com/CocoaPods/Specs.git'

target 'iOS-Tests' do
  platform :ios, '8.4'
  pod 'GSVersionComparator', :path => '../'
end

target 'OSX-Tests' do
  platform :osx, '10.9'
  pod 'GSVersionComparator', :path => '../'
end
